apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: autotrade-binance
  name: autotrade-binance
  namespace: coinauto
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: autotrade-binance
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: autotrade-binance
        version: v0.881
        app.kubernetes.io/name: autotrade-binance
        app.kubernetes.io/version: "v0.881"
    spec:
      containers:
      - envFrom:
        - secretRef:
            name: autotrade-binance-secret
        image: 172.10.30.11:5000/auto-coin/autotrade-binance-app:v0.881
        imagePullPolicy: IfNotPresent
        name: autotrade-binance
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
