apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# 기본 네임스페이스 지정
namespace: coinauto

# 공통 라벨 설정
commonLabels:
  app: autotrade-binance

# 리소스 목록
resources:
  - deployment.yaml

# 이미지 태그 오버레이 (필요 시 버전만 변경)
images:
  - name: 172.10.30.11:5000/auto-coin/autotrade-binance-app
    newTag: v0.81
